apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-auth
  namespace: azagents
stringData:
  # URL to the Azure DevOps organization
  AZP_URL: https://dev.azure.com/{{org-name}}

  # PAT with scope "Agent Pools - Read & manage"
  AZP_TOKEN: {{PAT-TOKEN}}

  # Agent Pool needs to be the same as in the ScaledJob
  AZP_POOL: self-hosted-agents-k8s
